- README.md
- dji_sdk/README.md
- dji_sdk/include/dji_sdk/DJI_LIB_ROS_Adapter.h
- dji_sdk/include/dji_sdk/dji_drone.h
- dji_sdk/include/dji_sdk/dji_sdk_node.h
- dji_sdk/launch/sdk_manifold.launch
- dji_sdk/launch/sdk_osx.launch
- dji_sdk/msg/A3GPS.msg
- dji_sdk/msg/A3RTK.msg
- dji_sdk/src/modules/dji_sdk_node_main.cpp
- dji_sdk_doc/whatToKnowI.md
- dji_sdk_lib/include/dji_sdk_lib/DJI_Type.h
- dji_sdk_web_groundstation/README.md
Some amendments to adapt the latest Onboard-SDK libraries.
> Adaption to the updated lib

- dji_sdk/src/dji_sdk/dji_drone.py
Because of this miss spelling, I couldn't use the "attitude_control()" function.
> amended the miss of spelling "attitude_conrol" to "attitude_control"

- dji_sdk/src/modules/dji_sdk_node_mission_services.cpp
- dji_sdk/src/modules/dji_sdk_node_publisher.cpp
- dji_sdk/src/modules/dji_sdk_node_services.cpp
1. Fix missing return values for service callback
2. Remove misleading comments
> Fix missing return values for service callback

- dji_sdk/src/modules/dji_sdk_node_services.cpp
> Enums from SRV file

- dji_sdk/include/dji_sdk/dji_sdk_node.h
- dji_sdk/src/modules/dji_sdk_node.cpp
- dji_sdk/src/modules/dji_sdk_node_publisher.cpp
Adding odometry publisher for show drone odometry in ROS Rviz.
> Adding odometry publisher

- include/dji_osdk_ros/dji_vehicle_node.h
- include/dji_osdk_ros/vehicle_wrapper.h
- src/dji_osdk_ros/dji_vehicle_node.cpp
- src/dji_osdk_ros/flight_control_node.cpp
- src/dji_osdk_ros/modules/vehicle_wrapper.cpp
> feat:add interface of upwards avoid enable

- src/dji_osdk_ros_obsoleted/CMakeLists.txt
Resolves issue #342 catkin build and install fails
> Fix catkin build install

- src/dji_osdk_ros/telemetry_node.cpp
> fixed:fixed thread block of telemetry sample and make it more clearly

- include/dji_osdk_ros/common_type.h
- include/dji_osdk_ros/dji_vehicle_node.h
- include/dji_osdk_ros/vehicle_wrapper.h
- src/dji_osdk_ros/dji_vehicle_node.cpp
- src/dji_osdk_ros/modules/vehicle_wrapper.cpp
> fixed:remove gimbal's data subscription to initDataSubscribeFromFC and

- src/dji_osdk_ros/dji_vehicle_node.cpp
- src/dji_osdk_ros/samples/CMakeLists.txt
> fixed:fix dji_vehicle_node's build problem without opencv

- src/dji_osdk_ros/samples/mission_node.cpp
> docs:add note about waypoint mission just adapt to M210V2

- CMakeLists.txt
- include/dji_osdk_ros/dji_vehicle_node.h
- include/dji_osdk_ros/vehicle_wrapper.h
- src/dji_osdk_ros/dji_vehicle_node.cpp
- src/dji_osdk_ros/modules/vehicle_wrapper.cpp
- src/dji_osdk_ros/samples/flight_control_node.cpp
- srv/ObtainControlAuthority.srv
> feat:add obtain/release control authority service

- src/dji_osdk_ros/dji_vehicle_node.cpp
- src/dji_osdk_ros_obsoleted/modules/dji_sdk_node.cpp
> docs:change imu_publisher's angular velocity unit from rad/s^2 to rad/s

- src/dji_osdk_ros/samples/camera_stream_node.cpp
Provide new and old sample for camera_stream_node.
> new:provide new and old sample for camera_stream_node

- src/dji_osdk_ros/modules/dji_vehicle_node_publisher.cpp
H264 frames missing the timestamp
> Add timestamp to h264 frames

- src/dji_osdk_ros/modules/vehicle_wrapper.cpp
- src/dji_osdk_ros/samples/mission_node.cpp
- src/dji_osdk_ros/samples/waypointV2_node.cpp
> fixed:add obtain_ctrl_authority to mission_node,waypointV2_node

- src/dji_osdk_ros/dji_vehicle_node.cpp
- src/dji_osdk_ros/modules/vehicle_wrapper.cpp
- src/dji_osdk_ros/samples/gimbal_camera_control_node.cpp
- srv/CameraAperture.srv
Fix camera setting api and samples.
> fix:fix camera parameters setting code

- src/dji_osdk_ros/samples/telemetry_node.cpp
> fixed: fix telemetry_node:displayMode and rcConnection id 0

- CMakeLists.txt
- ReadMe.md
- include/dji_osdk_ros/dji_vehicle_node.h
- include/dji_osdk_ros/vehicle_wrapper.h
- src/dji_osdk_ros/dji_vehicle_node.cpp
- src/dji_osdk_ros/modules/vehicle_wrapper.cpp
- src/dji_osdk_ros/samples/gimbal_camera_control_node.cpp
- srv/CameraSetZoomPara.srv
> feat:add set camera zoom para service

- ReadMe.md
> docs:change readme about usb permission

- ReadMe.md
> docs:add install linsdl2 to readme

- msg/WaypointV2Action.msg
- src/dji_osdk_ros/modules/dji_vehicle_node_mission_services.cpp
> fixed:delete wp2 reach point trigger

- ReadMe.md
> docs:update readme for 4.1.0

- ReadMe.md
> fix:fix readme issue
